[versions]
kord = "0.17.0"
coroutines = "1.10.2"

[libraries]
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-voice = { module = "dev.kord:kord-voice", version.ref = "kord" }
kord-core-voice = { module = "dev.kord:kord-core-voice", version.ref = "kord"}
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
