[versions]
kord = "0.18.0"
coroutines = "1.10.2"
lavakord = "9.2.0"
lavasrc = "4.8.1"

[libraries]
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-voice = { module = "dev.kord:kord-voice", version.ref = "kord" }
kord-core-voice = { module = "dev.kord:kord-core-voice", version.ref = "kord" }
kord-rest = { module = "dev.kord:kord-rest", version.ref = "kord"}
kord-lavakord = { module = "dev.schlaubi.lavakord:kord", version.ref = "lavakord" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
lavakord = { module = "dev.schlaubi.lavakord:lavasrc-jvm", version.ref = "lavakord" }
lavasrc = { module = "com.github.topi314.lavasrc:lavasrc", version.ref = "lavasrc" }
lavasrc-protocol = { module = "com.github.topi314.lavasrc:lavasrc-protocol", version.ref = "lavasrc" }

[plugins]
